[package]
name = "flashkit"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = "0.3.32"
hex = "0.4.3"
nusb = "0.2.3"
rustix = { version = "1.1.4", features = ["fs","mount"] }
sha2 = "0.11.0"
sysinfo = "0.39.0"
thiserror = "2.0.18"
tokio = { version = "1.52.3", features = ["fs", "io-util", "macros", "rt-multi-thread", "sync"] }
tokio-stream = "0.1.18"
tracing = "0.1.44"

[lints.rust]
unsafe_code = "forbid"
missing_docs = "warn"
missing_debug_implementations = "warn"
unused_must_use = "deny"

[lints.clippy]
all = "deny"
indexing_slicing = "deny"
fallible_impl_from = "deny"
wildcard_enum_match_arm = "deny"
unneeded_field_pattern = "deny"
fn_params_excessive_bools = "deny"
must_use_candidate = "deny"

[dev-dependencies]
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
