[package]
name = "flashkit"
version = "0.1.0"
edition = "2024"

[dependencies]
hex = "0.4.3"
serde = { version = "1.0.228", features = ["derive"] }
sha2 = "0.11.0"
thiserror = "2.0.18"
tokio = { version = "1.52.3", features = ["fs", "io-util", "macros", "rt-multi-thread", "sync"] }
tokio-stream = "0.1.18"
tracing = "0.1.44"

[target.'cfg(unix)'.dependencies]
libc = "0.2.186"
rustix = { version = "1.1.4", features = ["param"] }

[target.'cfg(target_os = "linux")'.dependencies]
zbus = { version = "5.15.0", features = ["tokio"] }
zvariant = "5.11.0"

[target.'cfg(windows)'.dependencies.windows]
version = "0.62"
features = [
    "Data_Xml_Dom",
    "Win32_Security",
    "Win32_System_Threading",
    "Win32_UI_WindowsAndMessaging",
    "Win32_Storage",
    "Win32_System_Ioctl",
    "Win32_Storage_FileSystem",
    "Win32_System_IO",
    "Win32_Devices",
    "Win32_Devices_Properties",
    "Win32_Devices_DeviceAndDriverInstallation",
]

[lints.rust]
missing_docs = "warn"
missing_debug_implementations = "warn"
unused_must_use = "deny"

[lints.clippy]
all = "deny"
indexing_slicing = "deny"
fallible_impl_from = "deny"
wildcard_enum_match_arm = "deny"
unneeded_field_pattern = "deny"
fn_params_excessive_bools = "deny"
must_use_candidate = "deny"

[dev-dependencies]
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
tokio = { version = "1", features = ["full"] }
tempfile = "3"
sha2 = "0.11.0"
